spring:
  datasource:
#    url: jdbc:mysql://rio-post-db:3306/rio_post_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/rio_post_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
